#!/bin/bash
# Download and verify Linux distribution installers/ISO images
# https://github.com/nodiscc/distrib-dl

set -o errexit
set -o nounset
set -o pipefail
usage="$0 DISTRIBUTION1 [DISTRIBUTION2 DISTRIBUTION3 ...]"

##############################
# Configuration

### DEBIAN
# one of: amd64-i386 amd64 armel armhf i386 ia64 kfreebsd-amd64 kfreebsd-i386 mips mipsel multi-arch powerpc s390 s390x source sparc
debian_architecture="amd64-i386"
debian_version="10.2.0"
### TAILS
tails_architecture="amd64"
tails_version="4.0"
### KALI
kali_architecture="amd64"
kali_version="2018.4"
### CENTOS
centos_version_major="7"
centos_version_minor="1908"
### PROXMOX
# https://www.proxmox.com/en/downloads/category/iso-images-pve
proxmox_version="6.0-1"
### PFSENSE
pfsense_version="2.4.4"
pfsense_installer_type="vga" #serial or vga
### FREEBSD
freebsd_version="12.0"
### GENTOO (LIVE DVD)
# https://www.gentoo.org/downloads/signatures/
gentoo_release="20160704"
gentoo_image="livedvd-x86-amd64-32ul"
gentoo_gpg_fingerprint="D99EAC7379A850BCE47DA5F29E6438C817072058"
### VOID Linux
voidlinux_image="void-live-x86_64-20181111"
voidlinux_gpg_fingerprint="8DEBDA68B48282A4"
############################

# abort on errors
set -o errexit

download_dir="$PWD"
usage="$0 [OPTIONS] DISTRIBUTION1 [DISTRIBUTION2 DISTRIBUTION3 ...]
Available distributions: debian centos tails kali proxmox pfsense freebsd gentoo-live voidlinux
Options:
-c        only check that the url returns 200, don't download anything"

############################

function download_debian() {
    # Official netinstall image without firmwares (disabled)
    #debian_base_url="https://cdimage.debian.org/debian-cd/current/${architecture}/iso-cd/"
    #debian_iso_filename="debian-${debian_version}-${architecture}-netinst.iso"
    # Unofficial image including firmwares
    debian_base_url="https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/current/multi-arch/iso-cd/"
    debian_iso_filename="firmware-${debian_version}-${debian_architecture}-netinst.iso"
    debian_sums_url="${debian_base_url}/SHA512SUMS"
    debian_sums_sign_url="${debian_base_url}/SHA512SUMS.sign"
    if [[ ! -d "$download_dir/debian/" ]]; then mkdir --directory-prefix="$download_dir/debian/"; fi
    echo "Downloading Debian checksums and signature..."
    # shellcheck disable=SC2086
    wget $wget_opts --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/debian/" "$debian_sums_url"
    # shellcheck disable=SC2086
    wget $wget_opts --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/debian/" "$debian_sums_sign_url"
    echo "Verifying Debian signature..."
    gpg --verify "$download_dir/debian/SHA512SUMS.sign" "$download_dir/debian/SHA512SUMS"
    echo "Downloading Debian ISO image..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/debian/" "$debian_base_url/$debian_iso_filename"
    echo "Verifying Debian ISO image integrity..."
    cd "$download_dir/debian/" && sha512sum -c <(cat SHA512SUMS) && cd -
}

function download_centos() {
    # fingerprint: 6341 AB27 53D7 8A78 A7C2  7BB1 24C6 A8A7 F4A8 0EB5
    centos_base_url="https://ftp.osuosl.org/pub/centos/${centos_version_major}/isos/x86_64/"
    centos_iso_filename="CentOS-${centos_version_major}-x86_64-Minimal-${centos_version_minor}.iso"
    centos_iso_url="${centos_base_url}/${centos_iso_filename}"
    #centos_iso_url="${centos_base_url}/CentOS-7-live-GNOME-x86_64.iso" #Alternative live image w/ GNOME desktop, disabled
    centos_key_url="https://www.centos.org/keys/RPM-GPG-KEY-CentOS-${centos_version_major}"
    centos_sums_sign_url="${centos_base_url}/sha256sum.txt.asc"
    centos_sums_url="${centos_base_url}/sha256sum.txt"
    if [[ ! -d "$download_dir/centos/" ]]; then mkdir --directory-prefix="$download_dir/centos/"; fi
    echo "Downloading CentOS keys, cheksums and signature..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/centos/" "$centos_key_url"
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/centos/" "$centos_sums_url"
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/centos/" "$centos_sums_sign_url"
    echo "Importing CentOS GPG key..."
    gpg --import "$download_dir/centos/RPM-GPG-KEY-CentOS-${centos_version_major}"
    echo "Downloading CentOS ISO image..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/centos/" "$centos_iso_url"
    cd "$download_dir/centos/"
    echo "Verifying CentOS signature..."
    gpg --verify < sha256sum.txt.asc
    echo "Verifying CentOS ISO image integrity..."
    sha256sum -c <(grep "$centos_iso_filename" sha256sum.txt)
    cd -
}

function download_tails() {
    if [[ ! -d "$download_dir/tails/" ]]; then mkdir --directory-prefix="$download_dir/tails/"; fi
    tails_iso_url="https://dl.amnesia.boum.org/tails/stable/tails-${tails_architecture}-${tails_version}/tails-${tails_architecture}-${tails_version}.iso"
    tails_key_url="https://tails.boum.org/tails-signing.key"
    tails_sig_url="https://tails.boum.org/torrents/files/tails-${tails_architecture}-${tails_version}.iso.sig"
    echo "downloading Tails key and signature..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/tails/" "$tails_key_url"
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/tails/" "$tails_sig_url"
    echo "Importing tails GPG key..."
    gpg --import "$download_dir/tails/tails-signing.key"
    echo "downloading Tails ISO image"
    #Force HTTPS but ignore certificate checks since Tails CDN can point to other servers than dl.amnesia.boum.org
    # shellcheck disable=SC2086
    wget $wget_opts --continue --no-check-certificate --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/tails/" "$tails_iso_url"
    echo "verifying Tails signature..."
    tails_sig_filename="tails-${tails_architecture}-${tails_version}.iso.sig"
    tails_iso_filename="tails-${tails_architecture}-${tails_version}.iso"
    gpg --keyid-format 0xlong --verify "$download_dir/tails/$tails_sig_filename" "$download_dir/tails/$tails_iso_filename"
}

function download_kali() {
    kali_base_url="https://cdimage.kali.org/kali-$kali_version/"
    kali_iso_filename="kali-linux-$kali_version-$kali_architecture.iso"
    kali_key_url="https://www.kali.org/archive-key.asc"
    if [[ ! -d "$download_dir/kali/" ]]; then mkdir --directory-prefix="$download_dir/kali/"; fi
    echo "Downloading Kali checksums, key and signature..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/kali/" "$kali_base_url/SHA256SUMS"
    # shellcheck disable=SC2086
    wget $wget_opts --continue --no-verbose --show-progress -O "$download_dir/kali/SHA256SUMS.gpg" "$kali_base_url/SHA256SUMS.gpg"
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/kali/" "$kali_key_url"
    echo "[distrib-dl] INFO: Importing Kali GPG key..."
    gpg --import "$download_dir/kali/archive-key.asc"
    echo "Verifying Kali signature..."
    gpg --verify "$download_dir/kali/SHA256SUMS.gpg" "$download_dir/kali/SHA256SUMS"
    echo "[distrib-dl] INFO: Downloading Kali ISO image..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/kali/" "$kali_base_url/$kali_iso_filename"
    echo "[distrib-dl] INFO: Verifying Kali ISO image integrity..."
    cd "$download_dir/kali/" && sha256sum -c <(grep "$kali_iso_filename" SHA256SUMS) && cd -
}

function download_proxmox {
    # No list of available ISOs https://forum.proxmox.com/threads/wget-pmg-iso.42113/
    # https://www.proxmox.com/en/downloads/category/iso-images-pve
    # https://pve.proxmox.com/wiki/Roadmap
    # TODO checksums/gpg verify download
    if [[ ! -d "$download_dir/kali/" ]]; then mkdir --directory-prefix="$download_dir/kali/"; fi
    proxmox_base_url="https://www.proxmox.com/images/download/pve/iso/"
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/proxmox/" "$proxmox_base_url/proxmox-ve_$proxmox_version.iso"
}

function download_pfsense {
    # TODO add other architectures (currently only amd64 supported)
    # New York mirror (disabled)
    #pfsense_base_url="https://nyifiles.pfsense.org/mirror/downloads"
    # Frankfurt mirror (disabled)
    #pfsense_base_url="https://frafiles.pfsense.org/mirror/downloads"
    # Main site
    pfsense_base_url="https://files.pfsense.org/mirror/downloads"
    if [[ "$pfsense_installer_type" == "serial" ]]; then pfsense_is_serial="serial-"
        elif [[ "$pfsense_installer_type" == "vga" ]]; then pfsense_is_serial=""
        else echo "[distrib-dl] ERROR: invalid installer type for pfsense: $pfsense_installer_type"; exit 1
    fi
    pfsense_iso_filename="pfSense-CE-memstick-${pfsense_is_serial}${pfsense_version}-RELEASE-amd64.img.gz"
    pfsense_hashes_base_url="https://files.pfsense.org/hashes/"
    if [[ ! -d "$download_dir/pfsense/" ]]; then mkdir --directory-prefix="$download_dir/pfsense/"; fi
    echo "[distrib-dl] INFO: downloading pfsense checksums..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/pfsense/" "${pfsense_hashes_base_url}/${pfsense_iso_filename}.sha256"
    echo "[distrib-dl] INFO: downloading pfsense ISO image..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/pfsense/" "${pfsense_base_url}/${pfsense_iso_filename}"
    echo "[distrib-dl] INFO: verifying pfsense ISO image integrity..."
    cd "$download_dir/pfsense" && sha256sum --check "pfSense-CE-memstick-${pfsense_is_serial}${pfsense_version}-RELEASE-amd64.img.gz.sha256" && cd -
}

function download_freebsd() {
    freebsd_base_url="https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/${freebsd_version}"
    freebsd_iso_filename="FreeBSD-${freebsd_version}-RELEASE-amd64-memstick.img"
    freebsd_sums_filename="CHECKSUM.SHA512-FreeBSD-${freebsd_version}-RELEASE-amd64.asc"
    freebsd_sums_url="https://www.freebsd.org/releases/${freebsd_version}R/${freebsd_sums_filename}"
    freebsd_gpgkeyring_url="https://www.freebsd.org/doc/pgpkeyring.txt"
    if [[ ! -d "$download_dir/freebsd/" ]]; then mkdir --directory-prefix="$download_dir/freebsd/"; fi
    echo "[distrib-dl] INFO: Downloading freebsd keyring, checksums and signature..."
    # shellcheck disable=SC2086
    wget $wget_opts --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/freebsd/" "$freebsd_gpgkeyring_url"
    # shellcheck disable=SC2086
    wget $wget_opts --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/freebsd/" "$freebsd_sums_url"
    gpg --verify "freebsd/$freebsd_sums_filename"
    echo "[distrib-dl] INFO: Downloading freebsd ISO image..."
    # shellcheck disable=SC2086
    wget $wget_opts --continue --timestamping --no-verbose --show-progress --directory-prefix="$download_dir/freebsd/" "$freebsd_base_url/$freebsd_iso_filename"
    echo "Verifying freebsd ISO image integrity..."
    cd "$download_dir/freebsd/" && sha512sum --ignore-missing -c <(cat ${freebsd_sums_filename}) && cd -
}

function download_gentoo_live() {
    # https://www.gentoo.org/downloads/mirrors/
    gentoo_base_url="https://mirror.bytemark.co.uk/gentoo/releases/amd64/${gentoo_release}/"
    gentoo_iso_filename="${gentoo_image}-${gentoo_release}.iso"
    gentoo_sums_filename="${gentoo_iso_filename}.DIGESTS.asc"
    gentoo_gpgkeyring_filename="${gentoo_iso_filename}.DIGESTS.sig"
    if [[ ! -d "$download_dir/gentoo/" ]]; then mkdir -p "$download_dir/gentoo/"; fi
    echo "[distrib-dl] INFO: Downloading gentoo keyring, checksums and signature..."
    gpg --keyserver hkps://keys.gentoo.org --recv-keys "$gentoo_gpg_fingerprint"
    wget -N -nv --show-progress -P "$download_dir/gentoo/" "${gentoo_base_url}${gentoo_gpgkeyring_filename}"
    wget -N -nv --show-progress -P "$download_dir/gentoo/" "${gentoo_base_url}${gentoo_sums_filename}"
    gpg --verify "gentoo/${gentoo_sums_filename}"
    echo "[distrib-dl] INFO: Downloading Gentoo Live ISO image..."
    wget --continue -N -nv --show-progress -P "$download_dir/gentoo/" "${gentoo_base_url}/${gentoo_iso_filename}"
    echo "[distrib-dl] INFO: Verifying Gentoo Live ISO image integrity..."
    cd "$download_dir/gentoo/" && sha512sum --ignore-missing -c <(cat ${gentoo_sums_filename}) && cd -
}
 
 download_voidlinux() {
	# https://alpha.de.repo.voidlinux.org/live/current/
	voidlinux_base_url="https://alpha.de.repo.voidlinux.org/live/current/"
	voidlinux_iso_filename="${voidlinux_image}.iso"
	voidlinux_sums_filename="sha256sums.txt"  
	voidlinux_gpgkeyring_filename="sha256sums.txt.sig"
	if [[ ! -d "$download_dir/voidlinux/" ]]; then mkdir -p "$download_dir/voidlinux/"; fi
	echo "Downloading VoidLinux keyring, checksums and signature..."
	gpg  --keyid-format long --keyserver hkps://keyserver.ubuntu.com --recv-keys "$voidlinux_gpg_fingerprint" 
	wget -N -nv --show-progress -P "$download_dir/voidlinux/" "${voidlinux_base_url}${voidlinux_gpgkeyring_filename}"  
	wget -N -nv --show-progress -P "$download_dir/voidlinux/" "${voidlinux_base_url}${voidlinux_sums_filename}"
	echo "Downloading VoidLinux ISO image..."
	wget --continue -N -nv --show-progress -P "$download_dir/voidlinux/" "${voidlinux_base_url}/${voidlinux_iso_filename}"
	echo "Verifying VoidLinux ISO image integrity..."
	cd "$download_dir/voidlinux/" && sha256sum --ignore-missing -c <(cat ${voidlinux_sums_filename}) && cd -
}

function _main() {
    wget_opts=""
    while getopts ":c" opt; do
        case $opt in
            c) wget_opts="--spider"; shift;;
            \?) echo "[distrib-dl] ERROR: invalid option -$OPTARG" >&2; exit 1;;
        esac
    done

    for distribution in "$@"; do
        if [[ "$distribution" == "debian" ]] ; then download_debian; fi
        if [[ "$distribution" == "centos" ]] ; then download_centos; fi
        if [[ "$distribution" == "tails" ]] ; then download_tails; fi
        if [[ "$distribution" == "kali" ]] ; then download_kali; fi
        if [[ "$distribution" == "proxmox" ]] ; then download_proxmox; fi
        if [[ "$distribution" == "pfsense" ]] ; then download_pfsense; fi
        if [[ "$distribution" == "freebsd" ]] ; then download_freebsd; fi
        if [[ "$distribution" == "gentoo-live" ]] ; then download_gentoo_live; fi
        if [[ "$distribution" == "voidlinux" ]] ; then download_voidlinux; fi
        if [[ "$distribution" == "1" ]]; then echo "Usage: $usage"; exit 1; fi
    done
}

#####################

_main "$@"
