#!/usr/bin/env python3
"""Download and verify Linux distribution installers"""

import os
import sys
import subprocess
import argparse

# Configuration
config = {
    "debian_architecture": "amd64",
    "debian_version": "13.3.0",
    "debian_live_architecture": "amd64",
    "debian_live_desktop_environment": "xfce",
    "tails_architecture": "amd64",
    "tails_version": "7.4",
    "kali_architecture": "amd64",
    "kali_version": "2025.4",
    "kali_flavour": "installer",
    "proxmox_version": "8.4-1",
    "freebsd_version": "15.0",
    "debian_live_config_version": "4.2.0",
    "fedora_version_major": "43",
    "fedora_version_minor": "1.6",
    "ubuntu_architecture": "amd64",
    "ubuntu_version": "22.04.5",
    "archlinux_version": "2026.01.01"
}

# Global options
VERIFY = True
DOWNLOAD_DIR = os.getcwd()
WGET_OPTS = "--progress=dot:giga --no-verbose --timestamping"

def run_cmd(cmd):
    """Run shell command with real-time output, and handle errors."""
    process = subprocess.Popen(
        cmd,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        universal_newlines=True,
        bufsize=1
        )
    for line in iter(process.stdout.readline, ''):
        print(line.rstrip())
    process.stdout.close()
    return_code = process.wait()
    if return_code != 0:
        raise subprocess.CalledProcessError(return_code, cmd)

def download_file(url, dest_dir):
    """Download a file using wget."""
    print(f'[distrib-dl] downloading {url}')
    cmd = f"wget {WGET_OPTS} --directory-prefix='{dest_dir}/' '{url}'"
    run_cmd(cmd)

def download_and_verify(dest_dir, base_url, iso, sums, sig, key_url, key_filename, verify_flag):
    """Generic download and verification function."""
    os.makedirs(dest_dir, exist_ok=True)
    if sums:
        download_file(f"{base_url}/{sums}", dest_dir)
    if sig:
        download_file(f"{base_url}/{sig}", dest_dir)
    if key_url:
        download_file(key_url, dest_dir)
        key_file = key_filename
    else:
        key_file = None

    download_file(f"{base_url}/{iso}", dest_dir)

    if verify_flag and sig:
        verify_signature(dest_dir, sig, sums, key_file)

    if verify_flag:
        print("[distrib-dl] Verifying ISO integrity...")
        if "SHA512" in sums or "sha512" in sums.lower():
            algo = "sha512"
        elif "SHA256" in sums or "sha256" in sums.lower():
            algo = "sha256"
        else:
            algo = "sha256"
        cmd = f"cat '{os.path.join(dest_dir, sums)}' | (cd '{dest_dir}' && {algo}sum --check --ignore-missing)"
        run_cmd(cmd)

def verify_signature(dest_dir, sig_file, sums_file, key_file):
    """Verify GPG signature."""
    if key_file:
        cmd = f"gpg --import '{os.path.join(dest_dir, key_file)}'"
        run_cmd(cmd)
    cmd = f"gpg --keyid-format 0xlong --verify '{os.path.join(dest_dir, sig_file)}' '{os.path.join(dest_dir, sums_file)}'"
    run_cmd(cmd)

def download_debian():
    dest_dir = os.path.join(DOWNLOAD_DIR, "debian")
    base_url = f"https://cdimage.debian.org/debian-cd/current/{config['debian_architecture']}/iso-cd/"
    iso = f"debian-{config['debian_version']}-{config['debian_architecture']}-netinst.iso"
    sums = "SHA512SUMS"
    sig = "SHA512SUMS.sign"

    cmd = "gpg --keyserver keyring.debian.org --recv-keys 64E6EA7D 6294BE9B 09EA8AC3"
    run_cmd(cmd)

    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso,
        sums=sums,
        sig=sig,
        key_url=None,
        key_filename=None,
        verify_flag=VERIFY
    )

def download_debian_live():
    dest_dir = os.path.join(DOWNLOAD_DIR, "debian-live")
    base_url = f"https://cdimage.debian.org/cdimage/release/current-live/{config['debian_live_architecture']}/iso-hybrid/"
    iso = f"debian-live-{config['debian_version']}-{config['debian_live_architecture']}-{config['debian_live_desktop_environment']}.iso"
    sums = "SHA512SUMS"
    sig = "SHA512SUMS.sign"
    cmd = "gpg --keyserver hkps://keyring.debian.org --recv-keys DF9B9C49EAA9298432589D76DA87E80D6294BE9B"
    run_cmd(cmd)
    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso,
        sums=sums,
        sig=sig,
        key_url=None,
        key_filename=None,
        verify_flag=VERIFY
    )

def download_tails():
    dest_dir = os.path.join(DOWNLOAD_DIR, "tails")
    os.makedirs(dest_dir, exist_ok=True)
    iso_url = f"https://mirrors.wikimedia.org/tails/stable/tails-{config['tails_architecture']}-{config['tails_version']}/tails-{config['tails_architecture']}-{config['tails_version']}.iso"
    key_url = "https://tails.boum.org/tails-signing.key"
    sig_url = f"https://tails.boum.org/torrents/files/tails-{config['tails_architecture']}-{config['tails_version']}.iso.sig"
    download_file(key_url, dest_dir)
    download_file(sig_url, dest_dir)
    download_file(iso_url, dest_dir)
    if VERIFY:
        run_cmd(f"gpg --import '{dest_dir}/tails-signing.key'")
        run_cmd('gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys DBB802B258ACD84F')
        run_cmd(f"gpg --keyid-format 0xlong --verify '{dest_dir}/tails-{config['tails_architecture']}-{config['tails_version']}.iso.sig' '{dest_dir}/tails-{config['tails_architecture']}-{config['tails_version']}.iso'")

def download_kali():
    dest_dir = os.path.join(DOWNLOAD_DIR, "kali")
    base_url = f"https://cdimage.kali.org/kali-{config['kali_version']}/"
    iso = f"kali-linux-{config['kali_version']}-{config['kali_flavour']}-{config['kali_architecture']}.iso"
    sums = "SHA256SUMS"
    sig = "SHA256SUMS.gpg"
    key_url = "https://archive.kali.org/archive-key.asc"
    key_filename = "archive-key.asc"
    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso,
        sums=sums,
        sig=sig,
        key_url=key_url,
        key_filename=key_filename,
        verify_flag=VERIFY
    )

def download_proxmox():
    dest_dir = os.path.join(DOWNLOAD_DIR, "proxmox")
    base_url = "https://enterprise.proxmox.com/iso"
    iso = f"proxmox-ve_{config['proxmox_version']}.iso"
    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso,
        sums=None,
        sig=None,
        key_url=None,
        key_filename=None,
        verify_flag=False
    )

def download_freebsd():
    dest_dir = os.path.join(DOWNLOAD_DIR, "freebsd")
    base_url = f"https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/{config['freebsd_version']}"
    iso_filename = f"FreeBSD-{config['freebsd_version']}-RELEASE-amd64-memstick.img"
    sums_filename = f"CHECKSUM.SHA512-FreeBSD-{config['freebsd_version']}-RELEASE-amd64"
    keyring_url = "https://docs.freebsd.org/pgpkeys/pgpkeys.txt"
    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso_filename,
        sums=sums_filename,
        sig=None,
        key_url=keyring_url,
        key_filename="pgpkeys.txt",
        verify_flag=VERIFY
    )

def download_debian_live_config():
    dest_dir = os.path.join(DOWNLOAD_DIR, "debian-live-config")
    base_url = f"https://github.com/nodiscc/debian-live-config/releases/download/{config['debian_live_config_version']}/"
    iso = f"debian-live-config-{config['debian_live_config_version']}-debian-bookworm-amd64.iso"
    sums = "SHA512SUMS"
    sig = "SHA512SUMS.sign"
    key = f"{base_url}debian-live-config-release.key"
    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso,
        sums=sums,
        sig=sig,
        key_url=key,
        key_filename=None,
        verify_flag=False
    )

def download_fedora():
    dest_dir = os.path.join(DOWNLOAD_DIR, "fedora")
    base_url = f"https://download.fedoraproject.org/pub/fedora/linux/releases/{config['fedora_version_major']}/Workstation/x86_64/iso"
    iso = f"Fedora-Workstation-Live-{config['fedora_version_major']}-{config['fedora_version_minor']}.x86_64.iso"
    sums = f"Fedora-Workstation-{config['fedora_version_major']}-{config['fedora_version_minor']}-x86_64-CHECKSUM"
    key = "https://fedoraproject.org/fedora.gpg"
    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso,
        sums=sums,
        sig=None,
        key_url=key,
        key_filename=None,
        verify_flag=VERIFY
    )

def download_ubuntu():
    dest_dir = os.path.join(DOWNLOAD_DIR, "ubuntu")
    base_url = f"https://releases.ubuntu.com/{config['ubuntu_version']}"
    iso = f"ubuntu-{config['ubuntu_version']}-desktop-{config['ubuntu_architecture']}.iso"
    sums = "SHA256SUMS"
    sig = "SHA256SUMS.gpg"

    cmd = "gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys D94AA3F0EFE21092"
    run_cmd(cmd)

    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso,
        sums=sums,
        sig=sig,
        key_url=None,
        key_filename=None,
        verify_flag=VERIFY
    )

def download_archlinux():
    dest_dir = os.path.join(DOWNLOAD_DIR, "archlinux")
    base_url = f"https://geo.mirror.pkgbuild.com/iso/{config['archlinux_version']}"
    iso_filename = "archlinux-x86_64.iso"
    sums_filename = "sha256sums.txt"
    sig_filename = "archlinux-x86_64.iso.sig"
    sums_url = f"https://archlinux.org/iso/{config['archlinux_version']}/{sums_filename}"
    download_file(sums_url, dest_dir)

    if VERIFY:
        run_cmd("gpg --auto-key-locate clear,wkd -v --locate-external-key pierre@archlinux.org")

    download_and_verify(
        dest_dir=dest_dir,
        base_url=base_url,
        iso=iso_filename,
        sums=sums_filename,
        sig=sig_filename,
        key_url=None,
        key_filename=None,
        verify_flag=VERIFY
    )

def main():
    parser = argparse.ArgumentParser(description="""Download and verify Linux distribution installers""")
    parser.add_argument("-c", action="store_true", help="Only check URL, don't download")
    parser.add_argument("-d", dest="download_dir", help="Specify base download directory")
    parser.add_argument("distributions", nargs="*", help="Distributions to download (archlinux debian debian-live debian-live-config fedora freebsd kali proxmox tails ubuntu, or all)")
    args = parser.parse_args()

    if args.c:
        global WGET_OPTS
        global VERIFY
        WGET_OPTS = "--spider"
        VERIFY = False
    if args.download_dir:
        global DOWNLOAD_DIR
        DOWNLOAD_DIR = args.download_dir

    distributions = args.distributions

    if not distributions or "all" in distributions:
        functions = [
            download_debian, download_debian_live, download_tails, download_kali,
            download_proxmox, download_freebsd, download_debian_live_config,
            download_fedora, download_ubuntu, download_archlinux
        ]
        for func in functions:
            func()
    else:
        for dist in distributions:
            if dist == "debian":
                download_debian()
            elif dist == "debian-live":
                download_debian_live()
            elif dist == "tails":
                download_tails()
            elif dist == "kali":
                download_kali()
            elif dist == "proxmox":
                download_proxmox()
            elif dist == "freebsd":
                download_freebsd()
            elif dist == "debian-live-config":
                download_debian_live_config()
            elif dist == "fedora":
                download_fedora()
            elif dist == "ubuntu":
                download_ubuntu()
            elif dist == "archlinux":
                download_archlinux()
            elif dist == "all":
                # Already handled above
                pass
            else:
                print(f"[distrib-dl] ERROR: Invalid distribution '{dist}'")
                sys.exit(1)

if __name__ == "__main__":
    main()
